### ISSUE TITLE
Time zone for dates is UTC and we don't need the time.

### ISSUE THREAD

**Issue by Ndemco** [Ndemco/task-manager-backend#2]

**Comment by Ndemco** [comment]
This issue has been resolved by providing adding an offset on the front end.

**Comment by llwp** [comment]
ugh. that means the data in the back end is always going to be wrong? ... curious about the choice.  bad data is a constant problem in enterprises. if you had to for a deadline, thats fine; but best practice is to backlog an issue for fix/update.  just my $0.02 ;) feel free to ignore.
